site_name: 细胞高质量数据标准 v1
site_url: https://cell-standard.readthedocs.io/
repo_url: https://github.com/Biometeor/cell-standard
repo_name: cell-standard
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - admonition
  - pymdownx.superfences

nav:
  - 首页: index.md
